ifdef CONFIG_MACH_MSM7201A_SURF
	obj-$(CONFIG_MSM_CAMERA) += 7x0x/
else
obj-$(CONFIG_MSM_CAMERA) += msm_camera.o msm_v4l2.o
obj-$(CONFIG_MSM_CAMERA_FLASH) += flash.o
obj-$(CONFIG_ARCH_MSM_ARM11) += msm_vfe7x.o msm_io7x.o
obj-$(CONFIG_ARCH_MSM_SCORPION) += msm_vfe8x.o msm_vfe8x_proc.o msm_io8x.o
endif
obj-$(CONFIG_MT9T013) += mt9t013.o mt9t013_reg.o mt9t013_byd.o mt9t013_liteon.o
obj-$(CONFIG_MT9D112) += mt9d112.o mt9d112_reg.o
obj-$(CONFIG_MT9P012) += mt9p012_reg.o
obj-$(CONFIG_MSM_CAMERA_AF_FOXCONN) += mt9p012_fox.o
obj-$(CONFIG_MSM_CAMERA_AF_BAM) += mt9p012_bam.o
obj-$(CONFIG_MSM_CAMERA_AF_KM) += mt9p012_km.o
obj-$(CONFIG_S5K3E2FX) += s5k3e2fx.o
obj-$(CONFIG_VB6801) += vb6801.o
obj-$(CONFIG_HUAWEI_CAMERA_SENSOR_OV3647) +=  ov3647.o
obj-$(CONFIG_HUAWEI_CAMERA_SENSOR_OV7690) +=  ov7690.o
obj-$(CONFIG_HUAWEI_CAMERA_SENSOR_HIMAX0356) +=  himax0356.o
obj-$(CONFIG_ARCH_MSM_ARM11) += msm_io7x.o
